print("="*50)
print("        MY PROFILE")
print("="*50)
print("Name      : Manthan Dodhiwala")
print("Course    : FYCS")
print("Age       : 18")
print("DOB       : 16-04-2008")
print("College   : Sheth L.U.J & Sir M.V College")
print("City      : Mumbai")
print("="*50)
